spring.application.name=cam66

spring.datasource.url = jdbc:postgresql://localhost:5432/cam66
spring.datasource.username = postgres
#spring.datasource.password = #1Qazse4
spring.datasource.password = cam66
spring.sql.init.password=admin
spring.datasource.driverClassName=org.postgresql.Driver
server.port=8085

# Mostrar SQL
logging.level.org.hibernate.SQL=DEBUG

# Mostrar valores de parámetros
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
